### ISSUE TITLE
Delete `initlog` method

### ISSUE THREAD

**Issue by Roenski** [TheSystemDevelopmentKit/thesdk#36]
@mkosunen Can this method be deleted? It's not used elsewhere in TheSyDeKick project. It throws an error anyway for undefined `cgreen`, `cend`, and `self`. It should either be fixed or removed.

**Comment by sporrasm** [comment]
+1, tried using it to change the logfile to something more reasonable to debug things. Just crashed whole darn thing. But it would be nice to be able to set the logfile path. So fixing is a far better solution IMO.

**Comment by mkosunen** [comment]
Colors defined in #44 . This method was created by @ojarvin , and I assume he had a reason to create it, so I'd rather fix it for now.

@Roenski , could you review
